# Generated by Django 5.0 on 2024-01-03 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('password_generator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='contact',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
